import { sqliteTable, text, integer, real, index } from 'drizzle-orm/sqlite-core';

export const messages = sqliteTable(
  'messages',
  {
    id: text('id').primaryKey(), // WhatsApp message key.id — dedup key
    contactJid: text('contact_jid').notNull(),
    fromMe: integer('from_me', { mode: 'boolean' }).notNull(),
    body: text('body').notNull().default(''),
    timestamp: integer('timestamp').notNull(), // Unix ms
    processed: integer('processed', { mode: 'boolean' }).default(false),
    createdAt: integer('created_at')
      .notNull()
      .$defaultFn(() => Date.now()),
  },
  (table) => [
    index('idx_messages_contact_ts').on(table.contactJid, table.timestamp),
  ],
);

export const contacts = sqliteTable('contacts', {
  jid: text('jid').primaryKey(),
  name: text('name'),
  mode: text('mode').notNull().default('off'), // 'off' | 'draft' | 'auto'
  relationship: text('relationship'),
  customInstructions: text('custom_instructions'),
  styleSummary: text('style_summary'), // Gemini-generated style analysis text, nullable
  snoozeUntil: integer('snooze_until'), // Unix ms timestamp for snooze expiry, null = not snoozed
  consecutiveAutoCount: integer('consecutive_auto_count').default(0), // counter for auto-reply cap
  voiceReplyEnabled: integer('voice_reply_enabled', { mode: 'boolean' })
    .notNull()
    .default(true),
  voiceId: text('voice_id'), // nullable — per-contact voice override
  createdAt: integer('created_at')
    .notNull()
    .$defaultFn(() => Date.now()),
  updatedAt: integer('updated_at')
    .notNull()
    .$defaultFn(() => Date.now()),
});

export const drafts = sqliteTable('drafts', {
  id: text('id').primaryKey(), // UUID
  contactJid: text('contact_jid').notNull(),
  inReplyToMessageId: text('in_reply_to_message_id').notNull(),
  body: text('body').notNull(),
  isVoice: integer('is_voice', { mode: 'boolean' }).notNull().default(false),
  status: text('status').notNull().default('pending'), // 'pending' | 'sent' | 'rejected'
  createdAt: integer('created_at')
    .notNull()
    .$defaultFn(() => Date.now()),
  actionedAt: integer('actioned_at'),
});

export const groups = sqliteTable('groups', {
  id: text('id').primaryKey(), // WhatsApp group JID (e.g. 123456789@g.us)
  name: text('name'),
  travelBotActive: integer('travel_bot_active', { mode: 'boolean' }).notNull().default(true),
  keywordRulesActive: integer('keyword_rules_active', { mode: 'boolean' }).notNull().default(true),
  reminderDay: text('reminder_day'), // 'monday' | 'tuesday' | ... | 'sunday'
  reminderHour: integer('reminder_hour').default(9), // Hour (0-23) for weekly reminder
  calendarLink: text('calendar_link'),
  memberEmails: text('member_emails'), // JSON array stored as text e.g. '["a@b.com"]'
  createdAt: integer('created_at')
    .notNull()
    .$defaultFn(() => Date.now()),
  updatedAt: integer('updated_at')
    .notNull()
    .$defaultFn(() => Date.now()),
});

export const groupMessages = sqliteTable(
  'group_messages',
  {
    id: text('id').primaryKey(), // WhatsApp message key.id for dedup
    groupJid: text('group_jid').notNull(), // @g.us JID
    senderJid: text('sender_jid').notNull(), // Individual sender within group
    senderName: text('sender_name'), // pushName of sender, nullable
    fromMe: integer('from_me', { mode: 'boolean' }).notNull(),
    body: text('body').notNull().default(''),
    timestamp: integer('timestamp').notNull(), // Unix ms
    createdAt: integer('created_at')
      .notNull()
      .$defaultFn(() => Date.now()),
  },
  (table) => [
    index('idx_group_messages_group_ts').on(table.groupJid, table.timestamp),
  ],
);

export const calendarEvents = sqliteTable(
  'calendar_events',
  {
    id: text('id').primaryKey(), // UUID, generated by the app
    groupJid: text('group_jid').notNull(),
    messageId: text('message_id').notNull(), // Links to the triggering groupMessage.id
    calendarId: text('calendar_id').notNull(), // Google Calendar ID
    calendarEventId: text('calendar_event_id').notNull(), // Google Calendar event ID
    confirmationMsgId: text('confirmation_msg_id'), // WhatsApp msg ID of confirmation, nullable
    title: text('title').notNull(), // Event title
    eventDate: integer('event_date').notNull(), // Unix ms of the event date
    createdAt: integer('created_at')
      .notNull()
      .$defaultFn(() => Date.now()),
  },
  (table) => [
    index('idx_calendar_events_confirmation').on(table.confirmationMsgId),
    index('idx_calendar_events_group').on(table.groupJid),
  ],
);

export const settings = sqliteTable('settings', {
  key: text('key').primaryKey(),
  value: text('value').notNull(),
});

export const keywordRules = sqliteTable(
  'keyword_rules',
  {
    id: text('id').primaryKey(), // UUID, generated by the app
    groupJid: text('group_jid').notNull(), // The group this rule belongs to
    name: text('name').notNull(), // Human-readable rule name
    pattern: text('pattern').notNull(), // Keyword string or regex pattern
    isRegex: integer('is_regex', { mode: 'boolean' }).notNull().default(false),
    responseType: text('response_type').notNull(), // 'fixed' | 'ai'
    responseText: text('response_text'), // Template text for fixed responses
    aiInstructions: text('ai_instructions'), // System prompt for AI responses
    enabled: integer('enabled', { mode: 'boolean' }).notNull().default(true),
    cooldownMs: integer('cooldown_ms').notNull().default(60000), // 60s default
    matchCount: integer('match_count').notNull().default(0),
    lastTriggeredAt: integer('last_triggered_at'), // Unix ms
    createdAt: integer('created_at')
      .notNull()
      .$defaultFn(() => Date.now()),
    updatedAt: integer('updated_at')
      .notNull()
      .$defaultFn(() => Date.now()),
  },
  (table) => [index('idx_keyword_rules_group').on(table.groupJid)],
);

// NOTE: group_messages_fts (FTS5 virtual table) exists outside Drizzle -- see drizzle/0010_fts5_group_messages.sql. Do NOT run db:generate after migration 0010.
export const tripContexts = sqliteTable('trip_contexts', {
  groupJid: text('group_jid').primaryKey(),
  destination: text('destination'),
  dates: text('dates'),
  contextSummary: text('context_summary'),
  lastClassifiedAt: integer('last_classified_at'), // Unix ms
  updatedAt: integer('updated_at')
    .notNull()
    .$defaultFn(() => Date.now()),
  // Phase 51 v2.1 — trip lifecycle columns (drizzle/0022_v21_phase51_trip_memory.sql)
  startDate: text('start_date'), // ISO-8601 YYYY-MM-DD
  endDate: text('end_date'), // ISO-8601 YYYY-MM-DD
  budgetByCategory: text('budget_by_category').notNull().default('{}'), // JSON: { flights, lodging, food, activities, transit, shopping, other }
  calendarId: text('calendar_id'), // null = primary Google Calendar
  status: text('status').notNull().default('active'), // 'active' | 'archived'
  briefingTime: text('briefing_time'), // 'HH:MM' in destination-tz
});

export const tripDecisions = sqliteTable(
  'trip_decisions',
  {
    id: text('id').primaryKey(), // UUID
    groupJid: text('group_jid').notNull(),
    type: text('type').notNull(), // 'destination' | 'accommodation' | 'activity' | 'transport' | 'dates' | 'budget' | 'open_question'
    value: text('value').notNull(),
    confidence: text('confidence').notNull().default('high'), // 'high' | 'medium' | 'low'
    sourceMessageId: text('source_message_id'),
    resolved: integer('resolved', { mode: 'boolean' }).notNull().default(false), // For open_question type
    createdAt: integer('created_at')
      .notNull()
      .$defaultFn(() => Date.now()),
    // Phase 51 v2.1 — structured columns (drizzle/0022_v21_phase51_trip_memory.sql).
    // Enums enforced in app layer (matches existing `type` column convention).
    proposedBy: text('proposed_by'), // phone/JID of group member, nullable
    category: text('category'), // 'flights' | 'lodging' | 'food' | 'activities' | 'transit' | 'shopping' | 'other'
    costAmount: real('cost_amount'), // numeric cost, nullable
    costCurrency: text('cost_currency'), // ISO-4217, nullable
    conflictsWith: text('conflicts_with').notNull().default('[]'), // JSON array of decision IDs
    origin: text('origin').notNull().default('inferred'), // 'inferred' | 'self_reported' | 'multimodal' | 'dashboard'
    metadata: text('metadata'), // JSON blob for edge-case fields
    archived: integer('archived', { mode: 'boolean' }).notNull().default(false), // flipped by auto-archive cron
  },
  (table) => [
    index('idx_trip_decisions_group').on(table.groupJid),
    index('idx_trip_decisions_type').on(table.groupJid, table.type),
  ],
);

// Phase 51 v2.1 — landing zone for expired trip_contexts rows.
// Daily 02:00 IST cron moves rows here when now > end_date + 3 days
// (see src/cron/archiveTripsCron.ts in a later plan).
export const tripArchive = sqliteTable(
  'trip_archive',
  {
    id: text('id').primaryKey(), // UUID (fresh per archive, distinct from groupJid)
    groupJid: text('group_jid').notNull(),
    destination: text('destination'),
    dates: text('dates'),
    contextSummary: text('context_summary'),
    lastClassifiedAt: integer('last_classified_at'), // Unix ms
    updatedAt: integer('updated_at').notNull(),
    startDate: text('start_date'),
    endDate: text('end_date'),
    budgetByCategory: text('budget_by_category').notNull().default('{}'),
    calendarId: text('calendar_id'),
    status: text('status').notNull(), // 'archived' at minimum
    briefingTime: text('briefing_time'),
    archivedAt: integer('archived_at').notNull(), // Unix ms when cron moved the row
  },
  (table) => [
    index('idx_trip_archive_group').on(table.groupJid),
    index('idx_trip_archive_end_date').on(table.endDate),
  ],
);

export const pendingSuggestions = sqliteTable(
  'pending_suggestions',
  {
    id: text('id').primaryKey(),
    groupJid: text('group_jid').notNull(),
    suggestionMsgId: text('suggestion_msg_id').notNull(),
    title: text('title').notNull(),
    eventDate: integer('event_date').notNull(), // Unix ms
    location: text('location'),
    description: text('description'),
    url: text('url'),
    calendarId: text('calendar_id').notNull(),
    calendarLink: text('calendar_link').notNull(),
    sourceMessageId: text('source_message_id').notNull(),
    senderName: text('sender_name'),
    expiresAt: integer('expires_at').notNull(), // Unix ms
    createdAt: integer('created_at')
      .notNull()
      .$defaultFn(() => Date.now()),
  },
  (table) => [
    index('idx_pending_suggestions_msg_id').on(table.suggestionMsgId),
    index('idx_pending_suggestions_group').on(table.groupJid),
    index('idx_pending_suggestions_expiry').on(table.expiresAt),
  ],
);

export const reminders = sqliteTable(
  'reminders',
  {
    id: text('id').primaryKey(), // UUID
    task: text('task').notNull(), // reminder description
    fireAt: integer('fire_at').notNull(), // Unix ms when reminder should fire
    status: text('status').notNull().default('pending'), // 'pending' | 'fired' | 'cancelled' | 'skipped'
    calendarEventId: text('calendar_event_id'), // Google Calendar event ID if created
    todoTaskId: text('todo_task_id'), // Google Tasks task ID if synced
    todoListId: text('todo_list_id'), // Google Tasks list ID
    source: text('source').notNull().default('user'), // 'user' | 'commitment'
    sourceContactJid: text('source_contact_jid'), // JID of contact whose message triggered commitment
    createdAt: integer('created_at')
      .notNull()
      .$defaultFn(() => Date.now()),
    updatedAt: integer('updated_at')
      .notNull()
      .$defaultFn(() => Date.now()),
  },
  (table) => [
    index('idx_reminders_status_fire').on(table.status, table.fireAt),
  ],
);

export const todoTasks = sqliteTable(
  'todo_tasks',
  {
    id: text('id').primaryKey(), // UUID
    task: text('task').notNull(), // detected task description
    contactJid: text('contact_jid').notNull(),
    contactName: text('contact_name'),
    originalText: text('original_text'), // message snippet
    todoTaskId: text('todo_task_id'), // Microsoft To Do task ID (null if not synced)
    todoListId: text('todo_list_id'), // Microsoft To Do list ID
    status: text('status').notNull().default('pending'), // 'pending' | 'synced' | 'cancelled' | 'failed'
    notificationMsgId: text('notification_msg_id'), // self-chat msg ID for cancel matching
    confidence: text('confidence').notNull().default('medium'), // 'high' | 'medium'
    createdAt: integer('created_at')
      .notNull()
      .$defaultFn(() => Date.now()),
    syncedAt: integer('synced_at'), // when pushed to To Do
  },
  (table) => [
    index('idx_todo_tasks_status').on(table.status),
    index('idx_todo_tasks_notification').on(table.notificationMsgId),
  ],
);

// Unified detected-or-requested actionable item (Phase 39, v1.8).
// Replaces the split commitment→reminders(source=commitment) + todoTasks write paths
// with one table that carries the full lifecycle: pending_approval → approved → fired
// (terminals: rejected, expired). See .planning/phases/39-actionables-data-model/39-CONTEXT.md.
export const actionables = sqliteTable(
  'actionables',
  {
    id: text('id').primaryKey(), // UUID
    sourceType: text('source_type').notNull(), // 'commitment' | 'task' | 'user_command'
    sourceContactJid: text('source_contact_jid').notNull(), // config.USER_JID for user_command
    sourceContactName: text('source_contact_name'), // snapshot at detection time
    sourceMessageId: text('source_message_id'), // WhatsApp trigger message id; null for user_command
    sourceMessageText: text('source_message_text').notNull().default(''), // full trigger snapshot
    detectedLanguage: text('detected_language').notNull().default('en'), // 'he' | 'en'
    originalDetectedTask: text('original_detected_task').notNull(), // IMMUTABLE — what was first extracted/typed
    task: text('task').notNull(), // mutable; replaced by `edit: <text>` approval grammar (Phase 41)
    status: text('status').notNull().default('pending_approval'), // 'pending_approval' | 'approved' | 'rejected' | 'fired' | 'expired'
    detectedAt: integer('detected_at').notNull(),
    fireAt: integer('fire_at'), // Unix ms; null for timeless tasks
    enrichedTitle: text('enriched_title'), // populated by Phase 42 on approval
    enrichedNote: text('enriched_note'), // populated by Phase 42 on approval
    todoTaskId: text('todo_task_id'), // Google Tasks id, set on approval+sync
    todoListId: text('todo_list_id'), // Google Tasks list id
    approvalPreviewMessageId: text('approval_preview_message_id'), // WhatsApp self-chat msg id for Phase 41 quoted-reply matching
    createdAt: integer('created_at')
      .notNull()
      .$defaultFn(() => Date.now()),
    updatedAt: integer('updated_at')
      .notNull()
      .$defaultFn(() => Date.now()),
  },
  (table) => [
    index('idx_actionables_status_detected').on(table.status, table.detectedAt),
    index('idx_actionables_preview_msg').on(table.approvalPreviewMessageId),
  ],
);

export const personalPendingEvents = sqliteTable(
  'personal_pending_events',
  {
    id: text('id').primaryKey(),
    sourceChatJid: text('source_chat_jid').notNull(),
    sourceChatName: text('source_chat_name'),
    senderJid: text('sender_jid').notNull(),
    senderName: text('sender_name'),
    sourceMessageId: text('source_message_id').notNull(),
    sourceMessageText: text('source_message_text').notNull(),
    title: text('title').notNull(),
    eventDate: integer('event_date').notNull(), // Unix ms
    location: text('location'),
    description: text('description'),
    url: text('url'),
    status: text('status').notNull().default('pending'), // 'pending' | 'approved' | 'rejected'
    notificationMsgId: text('notification_msg_id'), // self-chat msg ID for reply matching
    contentHash: text('content_hash'), // SHA-256 prefix for forwarded message dedup
    isAllDay: integer('is_all_day', { mode: 'boolean' }).notNull().default(false),
    calendarEventId: text('calendar_event_id'),
    createdAt: integer('created_at')
      .notNull()
      .$defaultFn(() => Date.now()),
  },
  (table) => [
    index('idx_personal_pending_status').on(table.status),
    index('idx_personal_pending_notification').on(table.notificationMsgId),
    index('idx_personal_pending_content_hash').on(table.contentHash),
  ],
);

export const scheduledMessages = sqliteTable(
  'scheduled_messages',
  {
    id: text('id').primaryKey().notNull(), // UUID
    type: text('type').notNull().default('text'), // 'text' | 'voice' | 'ai'
    content: text('content').notNull(), // user text, AI prompt, or text-to-speak
    status: text('status').notNull().default('pending'), // 'pending' | 'notified' | 'sending' | 'sent' | 'failed' | 'cancelled'
    scheduledAt: integer('scheduled_at').notNull(), // Unix ms, one-time fire time
    cronExpression: text('cron_expression'), // nullable, cron string for recurring (Phase 32)
    notificationMsgId: text('notification_msg_id'), // nullable, self-chat msg ID for cancel window (Phase 29)
    cancelRequestedAt: integer('cancel_requested_at'), // nullable, Unix ms when user cancels
    sentAt: integer('sent_at'), // nullable, Unix ms on successful send
    failCount: integer('fail_count').notNull().default(0),
    createdAt: integer('created_at')
      .notNull()
      .$defaultFn(() => Date.now()),
    updatedAt: integer('updated_at')
      .notNull()
      .$defaultFn(() => Date.now()),
  },
  (table) => [
    index('idx_scheduled_messages_status_at').on(table.status, table.scheduledAt),
    index('idx_scheduled_messages_notification').on(table.notificationMsgId),
  ],
);

export const scheduledMessageRecipients = sqliteTable(
  'scheduled_message_recipients',
  {
    id: text('id').primaryKey().notNull(), // UUID
    scheduledMessageId: text('scheduled_message_id').notNull(), // plain text FK to scheduled_messages.id
    recipientJid: text('recipient_jid').notNull(), // contact or group JID
    recipientType: text('recipient_type').notNull().default('contact'), // 'contact' | 'group'
    status: text('status').notNull().default('pending'), // 'pending' | 'sent' | 'failed' | 'cancelled'
    sentContent: text('sent_content'), // nullable, populated after AI/voice send for dashboard history
    failCount: integer('fail_count').notNull().default(0),
    sentAt: integer('sent_at'), // nullable, Unix ms
    createdAt: integer('created_at')
      .notNull()
      .$defaultFn(() => Date.now()),
  },
  (table) => [
    index('idx_smr_message_id').on(table.scheduledMessageId),
    index('idx_smr_status').on(table.status),
  ],
);
