import { sqliteTable, text, integer, index } from 'drizzle-orm/sqlite-core';

export const messages = sqliteTable(
  'messages',
  {
    id: text('id').primaryKey(), // WhatsApp message key.id — dedup key
    contactJid: text('contact_jid').notNull(),
    fromMe: integer('from_me', { mode: 'boolean' }).notNull(),
    body: text('body').notNull().default(''),
    timestamp: integer('timestamp').notNull(), // Unix ms
    processed: integer('processed', { mode: 'boolean' }).default(false),
    createdAt: integer('created_at')
      .notNull()
      .$defaultFn(() => Date.now()),
  },
  (table) => [
    index('idx_messages_contact_ts').on(table.contactJid, table.timestamp),
  ],
);

export const contacts = sqliteTable('contacts', {
  jid: text('jid').primaryKey(),
  name: text('name'),
  mode: text('mode').notNull().default('off'), // 'off' | 'draft' | 'auto'
  relationship: text('relationship'),
  customInstructions: text('custom_instructions'),
  styleSummary: text('style_summary'), // Gemini-generated style analysis text, nullable
  snoozeUntil: integer('snooze_until'), // Unix ms timestamp for snooze expiry, null = not snoozed
  consecutiveAutoCount: integer('consecutive_auto_count').default(0), // counter for auto-reply cap
  createdAt: integer('created_at')
    .notNull()
    .$defaultFn(() => Date.now()),
  updatedAt: integer('updated_at')
    .notNull()
    .$defaultFn(() => Date.now()),
});

export const drafts = sqliteTable('drafts', {
  id: text('id').primaryKey(), // UUID
  contactJid: text('contact_jid').notNull(),
  inReplyToMessageId: text('in_reply_to_message_id').notNull(),
  body: text('body').notNull(),
  status: text('status').notNull().default('pending'), // 'pending' | 'sent' | 'rejected'
  createdAt: integer('created_at')
    .notNull()
    .$defaultFn(() => Date.now()),
  actionedAt: integer('actioned_at'),
});

export const groups = sqliteTable('groups', {
  id: text('id').primaryKey(), // WhatsApp group JID (e.g. 123456789@g.us)
  name: text('name'),
  active: integer('active', { mode: 'boolean' }).notNull().default(true),
  reminderDay: text('reminder_day'), // 'monday' | 'tuesday' | ... | 'sunday'
  reminderHour: integer('reminder_hour').default(9), // Hour (0-23) for weekly reminder
  calendarLink: text('calendar_link'),
  memberEmails: text('member_emails'), // JSON array stored as text e.g. '["a@b.com"]'
  createdAt: integer('created_at')
    .notNull()
    .$defaultFn(() => Date.now()),
  updatedAt: integer('updated_at')
    .notNull()
    .$defaultFn(() => Date.now()),
});

export const groupMessages = sqliteTable(
  'group_messages',
  {
    id: text('id').primaryKey(), // WhatsApp message key.id for dedup
    groupJid: text('group_jid').notNull(), // @g.us JID
    senderJid: text('sender_jid').notNull(), // Individual sender within group
    senderName: text('sender_name'), // pushName of sender, nullable
    fromMe: integer('from_me', { mode: 'boolean' }).notNull(),
    body: text('body').notNull().default(''),
    timestamp: integer('timestamp').notNull(), // Unix ms
    createdAt: integer('created_at')
      .notNull()
      .$defaultFn(() => Date.now()),
  },
  (table) => [
    index('idx_group_messages_group_ts').on(table.groupJid, table.timestamp),
  ],
);

export const calendarEvents = sqliteTable(
  'calendar_events',
  {
    id: text('id').primaryKey(), // UUID, generated by the app
    groupJid: text('group_jid').notNull(),
    messageId: text('message_id').notNull(), // Links to the triggering groupMessage.id
    calendarId: text('calendar_id').notNull(), // Google Calendar ID
    calendarEventId: text('calendar_event_id').notNull(), // Google Calendar event ID
    confirmationMsgId: text('confirmation_msg_id'), // WhatsApp msg ID of confirmation, nullable
    title: text('title').notNull(), // Event title
    eventDate: integer('event_date').notNull(), // Unix ms of the event date
    createdAt: integer('created_at')
      .notNull()
      .$defaultFn(() => Date.now()),
  },
  (table) => [
    index('idx_calendar_events_confirmation').on(table.confirmationMsgId),
    index('idx_calendar_events_group').on(table.groupJid),
  ],
);
