import { sqliteTable, text, integer, index } from 'drizzle-orm/sqlite-core';

export const messages = sqliteTable(
  'messages',
  {
    id: text('id').primaryKey(), // WhatsApp message key.id — dedup key
    contactJid: text('contact_jid').notNull(),
    fromMe: integer('from_me', { mode: 'boolean' }).notNull(),
    body: text('body').notNull().default(''),
    timestamp: integer('timestamp').notNull(), // Unix ms
    processed: integer('processed', { mode: 'boolean' }).default(false),
    createdAt: integer('created_at')
      .notNull()
      .$defaultFn(() => Date.now()),
  },
  (table) => [
    index('idx_messages_contact_ts').on(table.contactJid, table.timestamp),
  ],
);

export const contacts = sqliteTable('contacts', {
  jid: text('jid').primaryKey(),
  name: text('name'),
  mode: text('mode').notNull().default('off'), // 'off' | 'draft' | 'auto'
  relationship: text('relationship'),
  customInstructions: text('custom_instructions'),
  styleSummary: text('style_summary'), // Gemini-generated style analysis text, nullable
  snoozeUntil: integer('snooze_until'), // Unix ms timestamp for snooze expiry, null = not snoozed
  consecutiveAutoCount: integer('consecutive_auto_count').default(0), // counter for auto-reply cap
  voiceReplyEnabled: integer('voice_reply_enabled', { mode: 'boolean' })
    .notNull()
    .default(true),
  voiceId: text('voice_id'), // nullable — per-contact voice override
  createdAt: integer('created_at')
    .notNull()
    .$defaultFn(() => Date.now()),
  updatedAt: integer('updated_at')
    .notNull()
    .$defaultFn(() => Date.now()),
});

export const drafts = sqliteTable('drafts', {
  id: text('id').primaryKey(), // UUID
  contactJid: text('contact_jid').notNull(),
  inReplyToMessageId: text('in_reply_to_message_id').notNull(),
  body: text('body').notNull(),
  isVoice: integer('is_voice', { mode: 'boolean' }).notNull().default(false),
  status: text('status').notNull().default('pending'), // 'pending' | 'sent' | 'rejected'
  createdAt: integer('created_at')
    .notNull()
    .$defaultFn(() => Date.now()),
  actionedAt: integer('actioned_at'),
});

export const groups = sqliteTable('groups', {
  id: text('id').primaryKey(), // WhatsApp group JID (e.g. 123456789@g.us)
  name: text('name'),
  active: integer('active', { mode: 'boolean' }).notNull().default(true),
  reminderDay: text('reminder_day'), // 'monday' | 'tuesday' | ... | 'sunday'
  reminderHour: integer('reminder_hour').default(9), // Hour (0-23) for weekly reminder
  calendarLink: text('calendar_link'),
  memberEmails: text('member_emails'), // JSON array stored as text e.g. '["a@b.com"]'
  createdAt: integer('created_at')
    .notNull()
    .$defaultFn(() => Date.now()),
  updatedAt: integer('updated_at')
    .notNull()
    .$defaultFn(() => Date.now()),
});

export const groupMessages = sqliteTable(
  'group_messages',
  {
    id: text('id').primaryKey(), // WhatsApp message key.id for dedup
    groupJid: text('group_jid').notNull(), // @g.us JID
    senderJid: text('sender_jid').notNull(), // Individual sender within group
    senderName: text('sender_name'), // pushName of sender, nullable
    fromMe: integer('from_me', { mode: 'boolean' }).notNull(),
    body: text('body').notNull().default(''),
    timestamp: integer('timestamp').notNull(), // Unix ms
    createdAt: integer('created_at')
      .notNull()
      .$defaultFn(() => Date.now()),
  },
  (table) => [
    index('idx_group_messages_group_ts').on(table.groupJid, table.timestamp),
  ],
);

export const calendarEvents = sqliteTable(
  'calendar_events',
  {
    id: text('id').primaryKey(), // UUID, generated by the app
    groupJid: text('group_jid').notNull(),
    messageId: text('message_id').notNull(), // Links to the triggering groupMessage.id
    calendarId: text('calendar_id').notNull(), // Google Calendar ID
    calendarEventId: text('calendar_event_id').notNull(), // Google Calendar event ID
    confirmationMsgId: text('confirmation_msg_id'), // WhatsApp msg ID of confirmation, nullable
    title: text('title').notNull(), // Event title
    eventDate: integer('event_date').notNull(), // Unix ms of the event date
    createdAt: integer('created_at')
      .notNull()
      .$defaultFn(() => Date.now()),
  },
  (table) => [
    index('idx_calendar_events_confirmation').on(table.confirmationMsgId),
    index('idx_calendar_events_group').on(table.groupJid),
  ],
);

export const settings = sqliteTable('settings', {
  key: text('key').primaryKey(),
  value: text('value').notNull(),
});

export const keywordRules = sqliteTable(
  'keyword_rules',
  {
    id: text('id').primaryKey(), // UUID, generated by the app
    groupJid: text('group_jid').notNull(), // The group this rule belongs to
    name: text('name').notNull(), // Human-readable rule name
    pattern: text('pattern').notNull(), // Keyword string or regex pattern
    isRegex: integer('is_regex', { mode: 'boolean' }).notNull().default(false),
    responseType: text('response_type').notNull(), // 'fixed' | 'ai'
    responseText: text('response_text'), // Template text for fixed responses
    aiInstructions: text('ai_instructions'), // System prompt for AI responses
    enabled: integer('enabled', { mode: 'boolean' }).notNull().default(true),
    cooldownMs: integer('cooldown_ms').notNull().default(60000), // 60s default
    matchCount: integer('match_count').notNull().default(0),
    lastTriggeredAt: integer('last_triggered_at'), // Unix ms
    createdAt: integer('created_at')
      .notNull()
      .$defaultFn(() => Date.now()),
    updatedAt: integer('updated_at')
      .notNull()
      .$defaultFn(() => Date.now()),
  },
  (table) => [index('idx_keyword_rules_group').on(table.groupJid)],
);

// NOTE: group_messages_fts (FTS5 virtual table) exists outside Drizzle -- see drizzle/0010_fts5_group_messages.sql. Do NOT run db:generate after migration 0010.
export const tripContexts = sqliteTable('trip_contexts', {
  groupJid: text('group_jid').primaryKey(),
  destination: text('destination'),
  dates: text('dates'),
  contextSummary: text('context_summary'),
  lastClassifiedAt: integer('last_classified_at'), // Unix ms
  updatedAt: integer('updated_at')
    .notNull()
    .$defaultFn(() => Date.now()),
});

export const tripDecisions = sqliteTable(
  'trip_decisions',
  {
    id: text('id').primaryKey(), // UUID
    groupJid: text('group_jid').notNull(),
    type: text('type').notNull(), // 'destination' | 'accommodation' | 'activity' | 'transport' | 'dates' | 'budget' | 'open_question'
    value: text('value').notNull(),
    confidence: text('confidence').notNull().default('high'), // 'high' | 'medium' | 'low'
    sourceMessageId: text('source_message_id'),
    resolved: integer('resolved', { mode: 'boolean' }).notNull().default(false), // For open_question type
    createdAt: integer('created_at')
      .notNull()
      .$defaultFn(() => Date.now()),
  },
  (table) => [
    index('idx_trip_decisions_group').on(table.groupJid),
    index('idx_trip_decisions_type').on(table.groupJid, table.type),
  ],
);

export const pendingSuggestions = sqliteTable(
  'pending_suggestions',
  {
    id: text('id').primaryKey(),
    groupJid: text('group_jid').notNull(),
    suggestionMsgId: text('suggestion_msg_id').notNull(),
    title: text('title').notNull(),
    eventDate: integer('event_date').notNull(), // Unix ms
    location: text('location'),
    description: text('description'),
    url: text('url'),
    calendarId: text('calendar_id').notNull(),
    calendarLink: text('calendar_link').notNull(),
    sourceMessageId: text('source_message_id').notNull(),
    senderName: text('sender_name'),
    expiresAt: integer('expires_at').notNull(), // Unix ms
    createdAt: integer('created_at')
      .notNull()
      .$defaultFn(() => Date.now()),
  },
  (table) => [
    index('idx_pending_suggestions_msg_id').on(table.suggestionMsgId),
    index('idx_pending_suggestions_group').on(table.groupJid),
    index('idx_pending_suggestions_expiry').on(table.expiresAt),
  ],
);
